// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.Command;
import java.util.function.DoubleSupplier;

import frc.robot.Constants;
import frc.robot.subsystems.Arm;

public class AmpPos extends Command {

    private final Arm m_arm;

    public AmpPos(Arm subsystem) 
    {
        m_arm = subsystem;
        addRequirements(m_arm);
    }

    @Override
    public void initialize() 
    {
        m_arm.setSetpoint(Constants.armConstants.armAmpPos);
        m_arm.enable();
    }

    @Override
    public boolean isFinished() {
        // This is set to true when we hit the setpoint.
        return m_arm.getController().atSetpoint();

    }

    @Override
    public boolean runsWhenDisabled() {
        return false;

    }
}
