// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj.PS5Controller;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.subsystems.Intake;
import frc.robot.subsystems.Shooter;

    
public class StartLaunch extends Command {

        private final Shooter m_shooter;
        private boolean m_done;
//private Timer m_shootTimer;
private PS5Controller m_ps5;
    public StartLaunch(Shooter subsystem,PS5Controller ps5) {

    m_ps5 = ps5;
        
        m_shooter = subsystem;
        m_done = false;
        addRequirements(m_shooter);

    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_shooter.Launch();
     //   m_shootTimer.start();

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() 
    {
          //  m_done = true;
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) 
    {
       // m_shooter.Stop();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        
        return m_done || m_ps5.getCrossButtonReleased();
    }
    
}
