// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj.PS5Controller;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.subsystems.Lift;

public class StartDeliverHooks extends Command {

    private final Lift m_lift;
    private boolean m_done;
    private PS5Controller m_ps5;

    public StartDeliverHooks(Lift lift, PS5Controller ps5) 
    {

        m_ps5 = ps5;
        m_lift = lift;
        m_done = false;
        addRequirements(m_lift);

    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() 
    {
        
     SmartDashboard.putNumber("before", 2);
        m_lift.Deliver();

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() 
    {
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) 
    {
        m_lift.Stop();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() 
    {

        return m_done || m_ps5.getCrossButtonReleased();
    }

}
