// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
//import frc.robot.Constants;
import frc.robot.Constants;

import com.revrobotics.CANSparkLowLevel;
import com.revrobotics.CANSparkMax;

///import edu.wpi.first.wpilibj.motorcontrol.PWMSparkMax;

public class Lift extends SubsystemBase {

    //private PWMSparkMax shooterMotor;
    private CANSparkMax liftMotor1;
    public Lift() {
        //shooterMotor = new PWMSparkMax(7);
        liftMotor1 = new CANSparkMax(Constants.motors.liftMotor1,CANSparkLowLevel.MotorType.kBrushed);
      
     }

    @Override
    public void periodic() {

    }

    @Override
    public void simulationPeriodic() {

    }

    public void Stop() 
    {
        liftMotor1.set(0);
        liftMotor1.stopMotor();
    }

    // public void Lift()
    // {
    //     liftMotor1.set(.3);
    // }

}
