// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.motorcontrol.PWMSparkMax;

public class Shooter extends SubsystemBase {
  
private PWMSparkMax shooterMotor;

    public Shooter() {
shooterMotor = new PWMSparkMax (7);
 addChild("Shooter Motor",shooterMotor);
 shooterMotor.setInverted(false);


    }

    @Override
    public void periodic() {

    }

    @Override
    public void simulationPeriodic() {

    }



    public void Launch () {

        shooterMotor.set(.5);

    }

    public void Collect (){
        
        shooterMotor.set(-.2);

}

}

